kind: pipeline
name: wiji

platform:
  os: linux
  arch: amd64


steps:

- name: run-tests
  image: python:3.7
  group: parallelo
  commands:
    - pwd
    - apt -y update; apt-get -y install pandoc curl
    - pip install -e .[dev,test]
    - find . -name '*.pyc' -delete;find . -name '__pycache__' -delete | xargs echo
    - coverage erase
    - coverage run --omit="*tests*,*cli/test_*,*examples/*,*.virtualenvs/*,*virtualenv/*,*.venv/*,*__init__*" -m unittest discover -v -s .
    - codecov
    - coverage report --show-missing --fail-under=70

    # branch coverage
    - coverage erase
    - coverage run --branch --omit="*tests*,*cli/test_*,*examples/*,*.virtualenvs/*,*virtualenv/*,*.venv/*,*__init__*" -m unittest discover -v -s .
    - codecov
    - coverage report --show-missing --fail-under=67
  environment:
    WIJI_DEBUG: 1
    PYTHONASYNCIODEBUG: 1
    CODECOV_TOKEN: "ecab2529-111c-4baa-8fbb-d679aba8e1f0"

- name: static-analysis
  image: python:3.7
  group: parallelo
  commands:
    - pwd
    - apt -y update; apt-get -y install pandoc curl
    - pip install -e .[dev,test]
    - find . -name '*.pyc' -delete;find . -name '__pycache__' -delete | xargs echo
    - black --line-length=100 --check . ||  { printf "\\n\\t please use black to format your code."; exit 77; }
    - flake8 .
    - pylint --enable=E --disable=W,R,C --unsafe-load-any-extension=y examples/ wiji/ tests/ cli/ documentation/
    - bandit -r --exclude .venv -ll .
    - mypy --show-column-numbers wiji/ #--strict
  environment:
    WIJI_DEBUG: 1
    PYTHONASYNCIODEBUG: 1

- name: run
  image: python:3.7
  group: parallelo
  commands:
    - pwd
    - wiji-cli --version
    - wiji-cli --config tests.testdata.cli.my_config.MyConfigInstance --dry-run
    - mypy --show-column-numbers wiji/ #--strict
  environment:
    WIJI_DEBUG: 1
    PYTHONASYNCIODEBUG: 1

- name: check-releases
  image: python:3.7
  group: parallelo
  commands:
    - pwd
    - apt -y update; apt-get -y install pandoc curl
    - find . -name '*.pyc' -delete;find . -name '__pycache__' -delete | xargs echo
    - |
      git remote set-branches --add origin master # https://github.com/travis-ci/travis-ci/issues/6069
      git fetch
      printf "\n current branch is $TRAVIS_BRANCH \n"
      if [ "$TRAVIS_BRANCH" == "master" ]; then
          printf "\n $TRAVIS_BRANCH branch, ignoring check for relese notes \n"
      else
          ChangedFiles=`git diff --name-only $TRAVIS_BRANCH remotes/origin/master`
          case "$ChangedFiles" in
              *CHANGELOG.*)
                  printf "\n Thanks, your commits include update to release notes. \n";;
              *)
                  printf "\n You should add release notes to CHANGELOG.md \n" && exit 77;;
          esac
      fi
  environment:
    WIJI_DEBUG: 1
    PYTHONASYNCIODEBUG: 1
