version: 2
jobs:
  run-tests:
    docker:
      - image: circleci/python:3.7
    environment:
      WIJI_DEBUG: 1
      PYTHONASYNCIODEBUG: 1 
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: test & coverage
          command: |
            pwd
            pip install -e .[dev,test]
            find . -name '*.pyc' -delete;find . -name '__pycache__' -delete | xargs echo
            coverage erase
            coverage run --omit="*tests*,*cli/test_*,*examples/*,*.virtualenvs/*,*virtualenv/*,*.venv/*,*__init__*" -m unittest discover -v -s .
            codecov
            coverage report --show-missing --fail-under=70
      - run:
          name: test & branch coverage
          command: |
            # branch coverage
            coverage erase
            coverage run --branch --omit="*tests*,*cli/test_*,*examples/*,*.virtualenvs/*,*virtualenv/*,*.venv/*,*__init__*" -m unittest discover -v -s .
            codecov
            coverage report --show-missing --fail-under=67

  static-analysis:
    docker:
      - image: circleci/python:3.7
    environment:
      WIJI_DEBUG: 1
      PYTHONASYNCIODEBUG: 1 
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: static-analysis
          command: |
            pwd
            pip install -e .[dev,test]
            find . -name '*.pyc' -delete;find . -name '__pycache__' -delete | xargs echo
            black --line-length=100 --check . ||  { printf "\\n\\t please use black to format your code."; exit 77; }
            flake8 .
            pylint --enable=E --disable=W,R,C --unsafe-load-any-extension=y examples/ wiji/ tests/ cli/ documentation/
            bandit -r --exclude .venv -ll .
            mypy --show-column-numbers wiji/ #--strict

  run-wiji:
    docker:
      - image: circleci/python:3.7
    environment:
      WIJI_DEBUG: 1
      PYTHONASYNCIODEBUG: 1 
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: run-wiji
          command: |
            pwd
            wiji-cli --version
            wiji-cli --config tests.testdata.cli.my_config.MyConfigInstance --dry-run

  check-releases:
    docker:
      - image: circleci/python:3.7
    environment:
      WIJI_DEBUG: 1
      PYTHONASYNCIODEBUG: 1 
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: check-releases
          command: |
            pwd
            apt -y update; apt-get -y install pandoc curl
            find . -name '*.pyc' -delete;find . -name '__pycache__' -delete | xargs echo
            |
              git remote set-branches --add origin master # https://github.com/travis-ci/travis-ci/issues/6069
              git fetch
              printf "\n current branch is $TRAVIS_BRANCH \n"
              if [ "$TRAVIS_BRANCH" == "master" ]; then
                  printf "\n $TRAVIS_BRANCH branch, ignoring check for relese notes \n"
              else
                  ChangedFiles=`git diff --name-only $TRAVIS_BRANCH remotes/origin/master`
                  case "$ChangedFiles" in
                      *CHANGELOG.*)
                          printf "\n Thanks, your commits include update to release notes. \n";;
                      *)
                          printf "\n You should add release notes to CHANGELOG.md \n" && exit 77;;
                  esac
              fi

workflows:
  version: 2
  flow1:
    jobs:
      - run-tests
      - static-analysis
      - run-wiji
      - check-releases:
          requires:
            - run-tests
            - static-analysis
            - run
          filters:
            branches:
              only:
                - master
